### ISSUE TITLE
Event Callback

### ISSUE THREAD

**Issue by Tortschi** [panda-media/rtmpmate#4]
Hello,

one Question. Is it possible to get Resolution and FPS from Source via Webhook like via On_publish?

Thanks for Answer

**Comment by oddengine** [comment]
No, just a few params will be sent. But if you pass any params while publishing, they will be sent, too.
rtmp://ip/live/streamName?**arg1**=xxx&**arg2**=xxx

**Comment by oddengine** [comment]
Hello,
I noticed that you were seeking solutions on this. 
If I can suggest, it is not suitable to provide such information via on_publish event. Because the server hasn't gotten these infos when the publish command arrived. But the publisher or streamer, such as OBS, would know what settings it is going to use. So  they can append them while sending the publish command, and our server will carry them.
This on_publish notify is usually designed to ask whether the publish behavior is allowed, which means the publisher must carry username, password or token by all means.
Hope this will be helpfull.
